name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pyyaml pandas numpy scikit-learn scipy mlflow matplotlib seaborn
      - name: Run data tests
        run: pytest tests/test_data.py -v --tb=short
      - name: Run model tests
        run: pytest tests/test_model.py -v --tb=short

  build:
    name: Build & Push to AWS ECR
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          ECR=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR/muril-hate-misinfo:latest .
          docker push $ECR/muril-hate-misinfo:latest
          echo "Pushed ✓"

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | \
              docker login --username AWS --password-stdin 679409142377.dkr.ecr.ap-south-1.amazonaws.com
            docker pull 679409142377.dkr.ecr.ap-south-1.amazonaws.com/muril-hate-misinfo:latest
            docker stop muril-app 2>/dev/null || true
            docker rm muril-app 2>/dev/null || true
            docker run -d --name muril-app --restart unless-stopped \
              -p 8501:8501 \
              679409142377.dkr.ecr.ap-south-1.amazonaws.com/muril-hate-misinfo:latest
            echo "Deployed ✓"
